name: 🐞 Carousel issue
about: Report an issue of the carousel functionality
labels: []
body:
  - type: checkboxes
    id: qa
    attributes:
      label: Check that this is really a bug
      options:
        - label: I confirm
          required: true

  - type: input
    id: reproduction
    attributes:
      label: Reproduction link
      description: Please provide a link to a repo that can reproduce the problem you ran into.
      placeholder: 'https://codesandbox.io/..'
    validations:
      required: false
  - type: textarea
    id: descr
    attributes:
      label: Bug description
      description: A clear and concise description of what the bug is
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen
    validations:
      required: false
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A concise description of what you're experiencing
    validations:
      required: false
  - type: input
    id: swiper
    attributes:
      label: Swiper version
      description: Exact release version or commit hash
      placeholder: e.g 1.2.1
    validations:
      required: true
  - type: checkboxes
    id: pr
    attributes:
      label: Would you like to open a PR for this bug?
      description: Before starting to work on PR it is recommended to get maintainers approval
      options:
        - label: I'm willing to open a PR
          required: false
