name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      # install dependencies
      - name: Run tests
        run: npm ci

      # build dist
      - name: Build dist
        run: npm run build:prod

